name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTc2Mjg4YTktZjI0NC00ZGE2LTlmNTgtMWYwNjYyYTVmYTBlIiwidGVuYW50X2lkIjoiMGQ5MTI0MzZkOGY4OWVlYjAwZDRiYWZhMWFmZGFlZDZhMGZkYTdmMTI0YWIxNzIyN2U0MjNiYjZlYmNlMDZiZSIsImludGVybmFsX3NlY3JldCI6ImI4YjkyMjMyLTk1NzctNDgyNi1hMTk5LTE4Y2ZiNDE2MTc2MCJ9.ir269TCUXj4WG7mUQXicRUQUMWSPKyaQrGbXEJZnUL8"
JWT_SECRET = "ruMzDZaSHa"